[GLOBAL]
pants_version = "2.11.0"
pythonpath = ["%(buildroot)s/packages/pants-plugins"]
backend_packages = [
    "pants.backend.python",
    "pants.backend.docker",
    "google_cloud_run",
]

[python]
interpreter_constraints = ["CPython==3.9.*"]
enable_resolves = true
lockfile_generator = "pex"

[source]
root_patterns = ["/packages"]

[docker]
default_repository = "{parent_directory}/{name}"

[anonymous-telemetry]
enabled = false